<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <RootNamespace>ET</RootNamespace>
    <AssemblyName>Robot.Hotfix</AssemblyName>
    <EnableDefaultCompileItems>false</EnableDefaultCompileItems>
    <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
    <OutputPath>..\..\..\Bin\</OutputPath>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
  </PropertyGroup>

  <ItemGroup>
    <Compile Include="..\..\..\Unity\Assets\Scripts\Hotfix\Robot\**\*.cs">
      <Link>Robot\%(RecursiveDir)%(FileName)%(Extension)</Link>
    </Compile>

    <ProjectReference Include="..\..\..\Share\Analyzer\Share.Analyzer.csproj" OutputItemType="Analyzer" ReferenceOutputAssembly="false" />
    <ProjectReference Include="..\..\..\Share\Share.SourceGenerator\Share.SourceGenerator.csproj" OutputItemType="Analyzer" ReferenceOutputAssembly="false" />
    <ProjectReference Include="..\..\Hotfix\DotNet.Hotfix.csproj" />
    <ProjectReference Include="..\Model\DotNet.Robot.Model.csproj" />
  </ItemGroup>
</Project>
